### ISSUE TITLE
Authorization header parsing can't handle unconventional values

### ISSUE THREAD

**Issue by roosmaa** [benoitc/gunicorn#1148]
The [_get_user](https://github.com/benoitc/gunicorn/blob/c8f820b95a559aec81167c854d7b0d869316ecb3/gunicorn/glogging.py#L381) method assumes that Basic authorization method is always used in the Authorization header. This is not true, especially for APIs which can have their own token format (not necessarily b64 encoded).

For instance `Authorization: Bearer whatever` header results in (Python 3.5; current master):

```
Traceback (most recent call last):
  File "/usr/src/deps/gunicorn/gunicorn/workers/async.py", line 116, in handle_request
    self.log.access(resp, req, environ, request_time)
  File "/usr/src/deps/gunicorn/gunicorn/glogging.py", line 287, in access
    request_time))
  File "/usr/src/deps/gunicorn/gunicorn/glogging.py", line 243, in atoms
    'u': self._get_user(environ) or '-',
  File "/usr/src/deps/gunicorn/gunicorn/glogging.py", line 392, in _get_user
    auth = auth.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
```

Depending on the input header value, the b64 operation itself can fail as well:

```
Traceback (most recent call last):
  File "/usr/src/deps/gunicorn/gunicorn/workers/async.py", line 116, in handle_request
    self.log.access(resp, req, environ, request_time)
  File "/usr/src/deps/gunicorn/gunicorn/glogging.py", line 287, in access
    request_time))
  File "/usr/src/deps/gunicorn/gunicorn/glogging.py", line 243, in atoms
    'u': self._get_user(environ) or '-',
  File "/usr/src/deps/gunicorn/gunicorn/glogging.py", line 390, in _get_user
    auth = base64.b64decode(auth[1].strip().encode('utf-8'))
  File "/usr/local/lib/python3.5/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

I suggest checking that the auth type is `Basic` before trying to do base64 operations on the 2nd part of the header. Handling those possible exceptions would also be nice, since someone might not know that `Basic` headers need to be base64 encoded.

**Comment by tilgovi** [comment]
:+1: we should fix this

- Should never cause a crash
- Should be quiet except maybe to warn once if the format seems like bad use of basic auth

**Comment by benoitc** [comment]
FYI the change to the logging have been introduced in 5f3dc8ed2bb5761846f20cfd15d1d44e711fbed1 . Any quick fix in mind?

**Comment by TheDodd** [comment]
It appears as though this issue has only been partially resolved. When passing in an authorization header as such `Authorization: Bearer whatever`, it appears as though gunicorn is causing the header to be filtered out before it reaches the underlying application. Other headers are not being filtered.

**Comment by benoitc** [comment]
@TheDodd thanks for the report. I will have a look on it for the next release.

**Comment by tilgovi** [comment]
@TheDodd are you sure this is a problem with gunicorn? In my testing, the "HTTP_AUTHORIZATION" key ends up in the environment just fine even with the access log enabled and a bogus authorization header value. However, some _frameworks_ may show `None` if they can't parse the header. For instance, with flask this will result in `request.authorization is None` but `request.headers['authorization']` has the right value.

I believe this is closed, but please re-open if you can describe what problem you are experiencing.
