### ISSUE TITLE
Gunicorn + gevent + unix socket -- can't reload

### ISSUE THREAD

**Issue by gbataille** [benoitc/gunicorn#1475]
Hello,

# Setup
Gunicorn 19.6.0
Django 1.9.5
gevent 1.1.2 (tried the latest 1.2.1, did not change anything)
rainbow-saddle 0.4.0

I use rainbow-saddle to be able to do hot reload, while using a deployment based on a `current` symlink to the latest release folder.
My understanding is that in such a setup, I need to restart the master (SIGUSR2) with also a chdir option so that the symlink is reevaluated by gunicorn on master spawn. rainbow-saddle does the USR2/WINCH/QUIT for me

# My config file
```
bind = "unix:/opt/cloud/socket.sock"
workers = 5
worker_class = "gevent"
max_requests = 100
max_requests_jitter = 10
graceful_timeout = 1200
chdir = '/opt/cloud/current/myapp'
pidfile = '/opt/cloud/gunicorn.pid'
user = 'ubuntu'
group = 'ubuntu'
loglevel = 'debug'
errorlog = '/var/log/gunicorn.error'
accesslog = '/var/log/gunicorn.access'
```

# Issue
I first start gunicorn through upstart (Ubuntu 14.04) - simple exec, no respawn configured
`exec rainbow-saddle /usr/local/bin/gunicorn pix4d.wsgi:application --config /opt/cloud/gunicorn_conf.py`

--> all is well. the socket is created, traffic works

Then I execute `sudo service gunicorn reload` to send a SIGHUP to the managed process (rainbow-saddle). I actually do that without changing the symlink or the code for the moment.

--> I see some expected logs in upstart
```
------------------------------------------------------------------------------
Starting new arbiter
------------------------------------------------------------------------------
------------------------------------------------------------------------------
New pidfile found: /tmp/rainbow-saddle-gunicorn-KBFme6.pid.2
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Stopping old arbiter with PID 5814
------------------------------------------------------------------------------
------------------------------------------------------------------------------
New arbiter PID is 5853
------------------------------------------------------------------------------
```
All is well

Then I execute a second time `sudo service gunicorn reload` (same: no symlink/code change)
--> same nice log, BUT the unix socket file disappears! (I guess when the old arbiter is stopped)

# Test I have done
* This does not seem to be an issue with the default sync worker
* Binding to a host:port seems even worse, I lost the nginx connection after the first gunicorn reload
(not sure why, could not see any error anywhere)

# Hint / idea
so I'm wondering:
the first time you start this setup, the gunicorn master is a child process of the rainbow-saddle one
```
ubuntu    5777     1  5 07:13 ?        00:00:00 /usr/bin/python /usr/local/bin/rainbow-saddle /usr/local/bin/gunicorn pix4d.wsgi:application --config /opt/cloud/gunicorn_conf.py
ubuntu    5779  5777 12 07:13 ?        00:00:00 /usr/bin/python /usr/local/bin/gunicorn pix4d.wsgi:application --config /opt/cloud/gunicorn_conf.py --pid /tmp/rainbow-saddle-gunicorn-KBFme6.pid
ubuntu    5784  5779 36 07:13 ?        00:00:00 /usr/bin/python /usr/local/bin/gunicorn pix4d.wsgi:application --config /opt/cloud/gunicorn_conf.py --pid /tmp/rainbow-saddle-gunicorn-KBFme6.pid
```

The second time, due to the new master being first a child of the old master and the old master then getting killed, the new master is actually orphan.
```
ubuntu    5777     1  0 07:13 ?        00:00:00 /usr/bin/python /usr/local/bin/rainbow-saddle /usr/local/bin/gunicorn pix4d.wsgi:application --config /opt/cloud/gunicorn_conf.py
ubuntu    5814     1  2 07:13 ?        00:00:00 /usr/bin/python /usr/local/bin/gunicorn pix4d.wsgi:application --config /opt/cloud/gunicorn_conf.py --pid /tmp/rainbow-saddle-gunicorn-KBFme6.pid
ubuntu    5819  5814 18 07:13 ?        00:00:00 /usr/bin/python /usr/local/bin/gunicorn pix4d.wsgi:application --config
```

I'm wondering if it's not what changes the decision making process as to whether to kill the socket (gunicorn is really shutting down) or keep it (hey, we are just switching master)

But then this does not happen in sync (but the concurrency would be very different, so who knows)

**Comment by benoitc** [comment]
did you try the latest master or 19.7.0 ? Should be solved there but let me know .

**Comment by gbataille** [comment]
alright. I thought I was on latest (and I could not find any such bug report anyway).

That seems to do the trick. I'll have to run it in dev/prod for a while like that but my manual testing and switching of things seems to work.

thanks, that'll make my prod a LOT better

**Comment by gbataille** [comment]
Hey @benoitc,

So it mostly works.
It still happens that the socket disappears. It tends to be rare, but it just happened today on our production.

Is there anything I can do to investigate, work around it, ... ?

**Comment by benoitc** [comment]
@gbataille any detail is welcome. If the socket disappear again can you provide us some logs?

the thing i'm not sure about your report is how you do this:

> Then I execute a second time sudo service gunicorn reload (same: no symlink/code change)
--> same nice log, BUT the unix socket file disappears! (I guess when the old arbiter is stopped)

is this right after the first reload? are there been any worker closed unexpectedly in between?

**Comment by gbataille** [comment]
Hey,

so the first bug details you can forget. That has been indeed "fixed" in
19.7.0.
Most of the time it works fine, but yesterday, it did not. I don't have a
way to reproduce it. not sure what I can do.

I actually have another problem where sometimes rainbow-saddle stops doing
anything while the process is still up.
I'm going to fork rainbow-saddle to add some trace and see if I can get to
something

**Comment by gbataille** [comment]
Ok so I found the root cause.
My deployment pattern is that I create a new folder, deploy the code, and change a symlink to the new code.
I'm then using rainbow-saddle to send the SIGUSR2/SIGTERM to the old arbiter and get a new one.
In my gunicorn config, I have `chdir = '/opt/cloud/current/'` so that the new arbiter redo the evaluation of the `current` symlink that has changed.

However, after 10 deploys, my old folders get cleaned up and then when gunicorn receives the SIGUSR2 I get
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 224, in run
    handler()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 304, in handle_usr2
    self.reexec()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 426, in reexec
    os.chdir(self.START_CTX['cwd'])
OSError: [Errno 2] No such file or directory: '/opt/cloud/releases/1234'
```

Seems like START_CTX['cwd'] is never updated. Is it by design? should it be when `chdir` is set in the config file?

**Comment by gbataille** [comment]
this pre_exec function seems to solve it in the gunicorn conf file
```
chdir = '/opt/cloud/current'

def pre_exec(server):
    import os
    os.chdir(chdir)
    server.START_CTX['cwd'] = os.getcwd()
```

Any reason not to have that behaviour as the normal one?

**Comment by benoitc** [comment]
@gbataille did you also try #1481 ?

**Comment by gbataille** [comment]
I did not but it does not seem to have any impact on the arbiter START_CTX,
so while it seems sensible, I'm not sure it'll solve my particular issue.
I'll see if I can test it tomorrow maybe, but I can't guarantee :(

**Comment by benoitc** [comment]
no activity since awhile. closing feel free to create a new ticket if needed.
