### ISSUE TITLE
python3 + gevent + statsd access logging broken

### ISSUE THREAD

**Issue by GraylinKim** [benoitc/gunicorn#1673]
I have been in the process of upgrading a gunicorn + gevent web application to Python3 and the statsd access logger throws the following exception on every request ([from here](https://github.com/benoitc/gunicorn/blob/master/gunicorn/instrument/statsd.py#L100)). The exception does not interfere with the request response but it does blow up my logs and prevent statsd instrumentation.

```
Traceback (most recent call last):
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gevent/pywsgi.py", line 1482, in handle
    handler.handle()
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gevent/pywsgi.py", line 454, in handle
    result = self.handle_one_request()
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gevent/pywsgi.py", line 671, in handle_one_request
    self.handle_one_response()
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gevent/pywsgi.py", line 964, in handle_one_response
    self.log_request()
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 217, in log_request
    self.server.log.access(resp, req_headers, self.environ, response_time)
  File "/Users/me/.venvs/hydra/lib/python3.6/site-packages/gunicorn/instrument/statsd.py", line 100, in access
    self.increment("gunicorn.request.status.%d" % status, 1)
TypeError: %d format: a number is required, not bytes
Fri Jan  5 15:55:03 2018 <Greenlet at 0x117747048: _handle_and_close_when_done(<bound method WSGIServer.handle of <PyWSGIServer a, <bound method StreamServer.do_close of <PyWSGIServ, (<gevent._socket3.socket [closed]  object, fd=-1, )> failed with TypeError
```

I looked into it and the gevent response status (set [here](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/ggevent.py#L220)) is always a ``bytes`` type in Python3 as of [this commit](https://github.com/gevent/gevent/commit/e8f89f12972104a86314afa84eb6f75642fa4c0d#diff-ee692367bef80509c57a0200fec7b488R652) in gevent ~2 years ago.

I'd appreciate any advice on how to keep this from blowing up my logs.

**Comment by tilgovi** [comment]
Interesting that you hit this while porting. I just tried a similar format string in Python 2 REPL and it also fails trying to format a `str` (bytes) with `%d`.

**Comment by tilgovi** [comment]
If you can track down an underlying issue, please don't hesitate to open a PR. Thanks for reporting it.

**Comment by GraylinKim** [comment]
The reason I hit this while porting is that in Python2 the status attribute is a ``str`` but in Python3 (see the linked commit) it is ``bytes``. This is important because if you look at the source method (first link above) it only splits and casts to an int if the status line is a string.

https://github.com/benoitc/gunicorn/blob/6171ac48857f1776fa445b0d27db4aeb5bbde357/gunicorn/instrument/statsd.py#L89-L100

The root issue is that the reported gunicorn status is now bytes. It is unclear what the correct course of action would be to fix this typing issue or what else might be affected.

**Comment by tilgovi** [comment]
Aha. We should be using `isinstance(status, six.string_types)`, I think.

**Comment by GraylinKim** [comment]
``six.string_types`` is a [still a string](https://pythonhosted.org/six/#six.string_types) in Python3 so I don't think that is what we are looking for. Also it is likely that other areas of gunicorn are expecting the response to have a string status type so I wonder if it would be better to fix it by decoding the status when constructing the GeventResponse.

https://github.com/benoitc/gunicorn/blob/5c9209321957b81645a789c0f89b0b7322cb62e9/gunicorn/workers/ggevent.py#L215-L225

**Comment by tilgovi** [comment]
Ah. If that's the case, we want `six.binary_type`. I had, perhaps, the right idea but the wrong execution :-D.

**Comment by berkerpeksag** [comment]
Should we add this to the next release?

**Comment by tilgovi** [comment]
Seems like an easy change we could get in.

**Comment by benoitc** [comment]
i believe this is fixed  with latest changes. closing the issue.  feel free to reopen it if needed

**Comment by eidsvold** [comment]
> i believe this is fixed with latest changes. closing the issue. feel free to reopen it if needed

I am using Python 3.8, `gunicorn==21.2.0` and `gevent==24.2.1`, and are still having the same issue as OP. I have to disable StatsD for my app to  be able to run Gunicorn with Gevent pyWSGI worker. There's an open PR #2336 that looks to fix the issue for me. Any updates on this?

**Comment by lee-burnette** [comment]
@eidsvold That PR has been merged! :tada:

**Comment by elendiastarman** [comment]
@eidsvold This PR has been merged! :tada:
